### ISSUE TITLE
Does not work in IE 11

### ISSUE THREAD

**Issue by xblabs** [estevanmaito/tailwind-dashboard#29]
considering roughly 1% of the web is still powered by IE 11, there should at least be some form of regressive fallback. Currently no screen in the demo is working. Apart from layout issues with grid, there should be at least some form of rendering possible, You can achieve that by replacing the ES6 object method shorthands by classic key : value notation. 

init-alpine.js : 21 

replace  toggleTheme() { 

with 

toggleTheme : function() {

**Comment by estevanmaito** [comment]
No plans to support unsupported broswers.
