### ISSUE TITLE
Use In nuxtjs

### ISSUE THREAD

**Issue by Obka** [estevanmaito/tailwind-dashboard#9]
hello dear
I love this dashboard and i need use it in nuxtjs , but i can't , can you help me or relise another version for nuxt?
thank you

**Comment by estevanmaito** [comment]
Hey!

Glad you like it!

There are no plans for a Nuxt/Vue versions, but you can share your questions here and I can try to help you converting it.

**Comment by Obka** [comment]
Hi dear friend
Thank you so much for guiding me and taking the time.
I'm going to convert this dashboard to Vue / Nuxtjs.
Can I start by asking you things here?

**Comment by forevergareth** [comment]
@Obka Fun fact a converted this app to nuxt. maybe ill actually publish a nuct version if @estevanmaito is okay with that.

**Comment by estevanmaito** [comment]
@forevergareth Go ahead 👍. I talked about it in another issue https://github.com/estevanmaito/windmill-dashboard/issues/2#issuecomment-654327183
